# примеры API-запросов

#@baseUrl = http://localhost:8000/api

# получение датчиков
#GET {{baseUrl}}/sensors/
GET http://localhost:8000/api/sensors/
Content-Type: application/json

###

# создание датчиков
#POST {{baseUrl}}/sensors/
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "JWS12-3",
  "description": "Датчик в ванной над колонкой"
}

###
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "WSG-31-gtx",
  "description": "Датчик в прихожей над дверью"
}

###

# обновление датчика
#PATCH {{baseUrl}}/sensors/1/
PATCH http://localhost:8000/api/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
#POST {{baseUrl}}/measurements/
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.4
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.2
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 21.3
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 22.0
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 21.1
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 25.3
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 25.5
}

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 25.0
}

###
# получение информации по датчику
#GET {{baseUrl}}/sensors/1/
http://localhost:8000/api/sensors/1/
Content-Type: application/json
